# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ce312972bcfeef609211b9a7c37f1212fb25eca5e6097587442b1e8adecba2ba6a1fd7768d6f0437782dba7c5960d40e7b4586451e91057f3eed4496e87598c

test:
  secret_key_base: c42d705181e4f87020601bc36ce4c7a8b6a0277fc8abef4825c9abccbca2dd6872e4ef99aba6207040b30b81b91b2bbf8ccea2d2efa6b3f858dc0f3acbe5d46c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
